kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Ops Manager UI/API: host port -> NodePort inside the cluster
      - containerPort: ${OM_NODEPORT}
        hostPort: ${OM_HOST_PORT}
        listenAddress: "0.0.0.0"
        protocol: TCP
