apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: ${RS_NAME}
  namespace: ${NAMESPACE}
spec:
  type: ReplicaSet
  members: 3
  version: ${MDB_VERSION}
  opsManager:
    configMapRef:
      name: my-project
  credentials: my-credentials
  persistent: true
  podSpec:
    persistence:
      single:
        storage: ${RS_STORAGE}
  additionalMongodConfig:
    storage:
      wiredTiger:
        engineConfig:
          cacheSizeGB: ${MONGOD_CACHE_GB}
